services:
  bot:
    build: .
    image: subway-telegram-bot:latest
    container_name: subway_telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
